# Generated by Django 3.2.7 on 2021-09-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_manager_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="skills",
            field=models.ManyToManyField(
                related_name="workers",
                through="jobs.WorkerSkill",
                to="jobs.Skill",
            ),
        ),
    ]
