# Generated by Django 3.2.7 on 2021-09-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_worker_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workerskill",
            old_name="workers_num",
            new_name="level",
        ),
    ]
