# Generated by Django 3.2.7 on 2021-09-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_worker_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(default=1)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionskills",
                        to="jobs.position",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionskills",
                        to="jobs.skill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="position",
            name="skills",
            field=models.ManyToManyField(
                related_name="positions",
                through="jobs.PositionSkill",
                to="jobs.Skill",
            ),
        ),
    ]
