# Generated by Django 3.2.7 on 2021-09-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_auto_20210911_1129"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("working_day", models.DateField(auto_now=True)),
                ("work_start", models.TimeField()),
                ("work_end", models.TimeField()),
                ("break_start", models.TimeField()),
                ("break_end", models.TimeField()),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="jobs.worker",
                    ),
                ),
            ],
        ),
    ]
