# Generated by Django 3.2.7 on 2021-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_timesheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="working_day",
            field=models.DateField(),
        ),
    ]
