# Generated by Django 3.2.7 on 2021-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_alter_timesheet_working_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Accepted"),
                    ("D", "Declined"),
                    ("P", "Pending"),
                ],
                default="P",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("B", "Busy")],
                default="A",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="status",
            field=models.CharField(
                choices=[("E", "Employed"), ("U", "Unemployed")],
                default="U",
                max_length=50,
            ),
        ),
    ]
