# Generated by Django 3.2.7 on 2021-09-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_auto_20210911_1620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "accepted"),
                    ("DECLINED", "declined"),
                    ("PENDING", "pending"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("BUSY", "busy")],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="status",
            field=models.CharField(
                choices=[
                    ("EMPLOYED", "employed"),
                    ("UNEMPLOYED", "unemployed"),
                ],
                default="UNEMPLOYED",
                max_length=50,
            ),
        ),
    ]
