# Generated by Django 3.2.7 on 2021-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_timesheet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("ACCEPTED", "accepted"),
                    ("DECLINED", "declined"),
                    ("CHANGED", "changed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
