# Generated by Django 3.2.7 on 2021-09-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0015_alter_timesheet_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("ACCEPTED", "accepted"),
                    ("DECLINED", "declined"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
